
# Create a folder
$ mkdir actions-runner && cd actions-runner
Copied! # Download the latest runner package
$ curl -o actions-runner-osx-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-osx-x64-2.317.0.tar.gz
# Optional: Validate the hash
$ echo "0b23ee79731522d9e1229d14d62c200e06ac9d7dddf5641966209a7700a43c14  actions-runner-osx-x64-2.317.0.tar.gz" | shasum -a 256 -c
# Extract the installer
$ tar xzf ./actions-runner-osx-x64-2.317.0.tar.gz
Configure
# Create the runner and start the configuration experience
$ ./config.sh --url https://github.com/JessaFay/JessaFay.github.io --token BJ3WNA4Q3TRC3J3DPNJLU53GSXBAO
# Last step, run it!
$ ./run.sh
Using your self-hosted runner
# Use this YAML in your workflow file for each job
runs-on: self-hosted
